"""Query pipeline — search wiki, gather context, synthesize answer."""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from wikiforge.config import WikiForgeConfig
from wikiforge.index import load_index, render_index_for_llm, save_index
from wikiforge.llm import call_llm, count_tokens
from wikiforge.schema import load_schema
from wikiforge.models import IndexEntry, WikiIndex
from wikiforge.prompts.query import build_query_messages
from wikiforge.vault import Vault

# Common English stop words to skip in keyword matching
_STOP_WORDS = frozenset(
    "a an the is are was were be been being have has had do does did "
    "will would shall should may might can could of in to for on with "
    "at by from as into through during before after above below between "
    "and or but not no nor so yet both either neither each every all "
    "any few more most other some such than too very what which who whom "
    "this that these those it its how when where why".split()
)


@dataclass
class QueryResult:
    answer: str
    articles_used: list[str]
    filed_back_path: str | None = None


def _tokenize(text: str) -> set[str]:
    """Simple keyword tokenizer."""
    words = re.findall(r"[a-z0-9]+", text.lower())
    return {w for w in words if w not in _STOP_WORDS and len(w) > 1}


def _score_entry(entry: IndexEntry, query_tokens: set[str]) -> float:
    """Score an index entry against query keywords."""
    entry_tokens = _tokenize(entry.title) | _tokenize(entry.summary)
    if not query_tokens:
        return 0.0
    overlap = query_tokens & entry_tokens
    # Title matches are worth more
    title_tokens = _tokenize(entry.title)
    title_overlap = query_tokens & title_tokens
    return len(overlap) + len(title_overlap) * 2


def _find_relevant_articles(
    index: WikiIndex,
    question: str,
    max_articles: int = 5,
) -> list[IndexEntry]:
    """Find the most relevant articles for a query."""
    query_tokens = _tokenize(question)
    scored = [
        (entry, _score_entry(entry, query_tokens))
        for entry in index.entries
    ]
    scored.sort(key=lambda x: x[1], reverse=True)
    # Return entries with score > 0, up to max
    return [entry for entry, score in scored[:max_articles] if score > 0]


def _load_article_content(vault: Vault, path: str) -> str | None:
    """Load article content from wiki directory."""
    full_path = vault.wiki_dir / path
    if full_path.exists():
        return full_path.read_text(encoding="utf-8")
    return None


def _slugify(text: str, max_len: int = 60) -> str:
    """Generate a kebab-case filename from text."""
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    if len(slug) > max_len:
        slug = slug[:max_len].rsplit("-", 1)[0]
    return slug or "query"


def run_query(
    vault: Vault,
    config: WikiForgeConfig,
    question: str,
    output_path: Path | None = None,
    file_back: bool = False,
) -> QueryResult:
    """Run a query against the wiki and return a synthesized answer."""
    index = load_index(vault.index_path)
    index_summary = render_index_for_llm(index)

    if not index.entries:
        return QueryResult(
            answer="The wiki is empty. Run `wf ingest` and `wf compile` first.",
            articles_used=[],
        )

    # Find relevant articles
    relevant = _find_relevant_articles(index, question)

    if not relevant:
        # Fall back to all articles if keyword matching found nothing
        relevant = index.entries[:5]

    # Load article contents
    article_contents: dict[str, str] = {}
    for entry in relevant:
        content = _load_article_content(vault, entry.path)
        if content:
            article_contents[entry.title] = content

    if not article_contents:
        return QueryResult(
            answer="No article content found. The wiki may need recompilation.",
            articles_used=[],
        )

    # Call LLM
    schema_context = load_schema(vault.schema_path)
    messages = build_query_messages(question, article_contents, index_summary, schema_context=schema_context)
    answer = call_llm(messages, model=config.llm.model)

    articles_used = list(article_contents.keys())

    # Write output file if path specified
    if output_path:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_content = (
            f"# Query: {question}\n\n"
            f"{answer}\n\n"
            f"---\n*Generated by WikiForge from: {', '.join(articles_used)}*\n"
        )
        output_path.write_text(output_content, encoding="utf-8")

    # File-back: save answer as a wiki page
    filed_back_path = None
    if file_back:
        filed_back_path = _file_back_answer(vault, index, question, answer, articles_used)

    # Log the query
    from wikiforge.log import append_log

    details = [f"Based on: {', '.join(articles_used)}"]
    if filed_back_path:
        details.append(f"Filed back to: wiki/{filed_back_path}")
    append_log(vault, "query", question[:80], details)

    return QueryResult(
        answer=answer,
        articles_used=articles_used,
        filed_back_path=filed_back_path,
    )


def _file_back_answer(
    vault: Vault,
    index,
    question: str,
    answer: str,
    articles_used: list[str],
) -> str:
    """Save a query answer as a wiki page and update the index."""
    slug = _slugify(question)
    filename = f"{slug}.md"
    category = "queries"

    # Ensure queries directory exists
    queries_dir = vault.wiki_dir / category
    queries_dir.mkdir(parents=True, exist_ok=True)

    # Build article content with frontmatter
    sources_yaml = "\n".join(f'  - "{s}"' for s in articles_used)
    content = (
        f"---\n"
        f'title: "{question}"\n'
        f'summary: "Query answer filed back into wiki"\n'
        f"sources:\n{sources_yaml}\n"
        f"tags:\n  - query\n  - filed-back\n"
        f'category: "{category}"\n'
        f"---\n\n"
        f"# {question}\n\n"
        f"{answer}\n\n"
        f"---\n*Filed back from query. Based on: {', '.join(articles_used)}*\n"
    )

    article_path = f"{category}/{filename}"
    (queries_dir / filename).write_text(content, encoding="utf-8")

    # Update index
    index.upsert(IndexEntry(
        path=article_path,
        title=question,
        summary="Query answer filed back into wiki",
        category=category,
    ))
    save_index(vault.index_path, index)

    return article_path
